FROM golang:1.26.2@sha256:b54cbf583d390341599d7bcbc062425c081105cc5ef6d170ced98ef9d047c716

WORKDIR /go/src/app
COPY go.mod go.sum .
RUN go mod download

COPY . .

RUN GOBIN=/usr/local/bin go install ./cmd/loadgen
CMD ["/usr/local/bin/loadgen"]
